### ISSUE TITLE
Update docs for 2.6.0 to reflect what's been added/changed

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake.org#79]
Update docs for 2.6.0 to reflect what's been added/changed:

- [x] Support added for index page under /tags (jbake-org/jbake#371) @manikmagar Fixed with #83 
- [x] Switch to flexmark from pegdown - do extensions need updating?? (jbake-org/jbake#376) @jonbullock
- [x] Include details of JBake environment variable support (jbake-org/jbake#182) @jonbullock
- [x] Support for ignoring folders from being processed (jbake-org/jbake#324) @manikmagar Fixed with #81 
- [x] Support for image existing in content folder (jbake-org/jbake#390) @manikmagar Fixed with #81 
- [x] Support for extra JAR's being added to classpath (jbake-org/jbake#230) @jonbullock
- [x] Added AsciiDoctorJ-diagram (jbake-org/jbake#385) @jonbullock
- [x] Extended watch mode to template & asset folders (jbake-org/jbake#384) @manikmagar Fixed with #82 
- [x] Automatic update of img src content (jbake-org/jbake#367) @manikmagar Fixed with #85 
- [x] Added nextContent/previousContent variables (jbake-org/jbake#364) - Fixed with #80 
- [x] Update to Java 7 (jbake-org/jbake#107) @jonbullock
- [x] -s option will override site.host variable (jbake-org/jbake#333) @jonbullock
- [x] Default doc type support (jbake-org/jbake#278) @jonbullock
- [x] Absolute path support (jbake-org/jbake#229) @jonbullock

**Comment by benelog** [comment]
Thank you for your documentation.
I am eagerly awaiting the 2.6.0.
